name: 'Terraform Preview'

on:
  workflow_dispatch:
    
permissions:
  contents: read
  id-token: write

jobs:
  preview:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: Setup Azure CLI
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az account show
               
